# Generated by Django 5.1.1 on 2024-10-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_category_products_image_products_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('lastname', models.CharField(default='', max_length=70)),
                ('title', models.CharField(default='', max_length=70)),
                ('detail', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
